const CONFIG=window.APP_CONFIG||{};
const configured=CONFIG.SUPABASE_URL&&!CONFIG.SUPABASE_URL.includes('YOUR-')&&CONFIG.SUPABASE_ANON_KEY&&!CONFIG.SUPABASE_ANON_KEY.includes('YOUR-');
const db=configured&&window.supabase?window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY):null;
const seedInstructors=[{id:'teacher-demo',name:'김배움',email:'teacher@baeumon.kr',phone:'010-2345-6789',bank_name:'국민은행',bank_account:'123-456-789012',account_holder:'김배움'}];
const store={get(k,f=[]){try{return JSON.parse(localStorage.getItem('baeumon_'+k))||f}catch{return f}},set(k,v){localStorage.setItem('baeumon_'+k,JSON.stringify(v))}};
if(!store.get('instructors').length)store.set('instructors',seedInstructors);
let currentUser=store.get('session',null),activePanel='requests',rows=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const typeName=t=>({completion:'수료증',level1:'1급 자격증',level2:'2급 자격증'}[t]||t);
const fmt=d=>d?new Date(d).toLocaleDateString('ko-KR'):'-';
function route(name,type){if((name==='report'||name==='dashboard')&&!currentUser){openLogin();return}$$('.page').forEach(x=>x.classList.toggle('active',x.id===name));$$('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===name));scrollTo({top:0});if(name==='apply')setApplyMode(type&&type!=='completion'?'license':'completion',type);if(name==='dashboard')loadDashboard();location.hash=name}
$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route,b.dataset.type));
function renderAuth(){const logged=!!currentUser;$$('.auth-only').forEach(x=>x.classList.toggle('hidden',!logged));$$('.admin-only').forEach(x=>x.classList.toggle('hidden',currentUser?.role!=='admin'));$('#login-open').classList.toggle('hidden',logged);$('#logout').classList.toggle('hidden',!logged);$('#user-badge').textContent=logged?`${currentUser.name} · ${currentUser.role==='admin'?'운영자':'강사'}`:'';if(logged)$('#report-instructor-name').value=currentUser.name||''}
function openLogin(){$('#login-dialog').showModal()}$('#login-open').onclick=openLogin;$('#hero-login').onclick=openLogin;$('#quick-report').onclick=()=>currentUser?route('report'):openLogin();$$('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#logout').onclick=async()=>{if(db)await db.auth.signOut();currentUser=null;store.set('session',null);renderAuth();route('home')};
$('#login-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));let user=null;if(db){const {data,error}=await db.auth.signInWithPassword({email:f.email,password:f.password});if(error)return msg('login-message',error.message,true);const {data:p}=await db.from('profiles').select('*').eq('id',data.user.id).single();user=p}else if(f.email==='admin@baeumon.kr'&&f.password==='admin123')user={id:'admin-demo',name:'정운영',email:f.email,role:'admin'};else if(f.email==='teacher@baeumon.kr'&&f.password==='teacher123')user={...seedInstructors[0],role:'instructor'};if(!user)return msg('login-message','아이디 또는 비밀번호를 확인해 주세요.',true);currentUser=user;store.set('session',user);renderAuth();e.target.closest('dialog').close();route('dashboard')};
$('#forgot-password').onclick=async()=>{const email=$('#login-form [name=email]').value;if(!email)return msg('login-message','먼저 이메일을 입력해 주세요.',true);if(db){const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});msg('login-message',error?error.message:'비밀번호 재설정 메일을 보냈습니다.',!!error)}else msg('login-message','미리보기에서는 위에 표시된 계정을 사용해 주세요.')};
function msg(id,text,error=false){const el=$('#'+id);el.textContent=text;el.style.color=error?'#b54332':'#256c54'}
async function instructors(){if(db){const {data}=await db.from('instructor_directory').select('*').order('name');return data||[]}return store.get('instructors',seedInstructors)}
async function fillInstructors(){const list=await instructors();$('#application-instructor').innerHTML='<option value="">강사를 선택해 주세요</option>'+list.map(i=>`<option value="${i.id}">${i.name}</option>`).join('');$('#application-instructor').onchange=()=>{const i=list.find(x=>x.id===$('#application-instructor').value);$('#bank-guide').textContent=i?.bank_name?`자격증비 입금 안내: ${i.bank_name} ${i.bank_account} (${i.account_holder})`:''}}
function setApplyMode(mode,type){const license=mode==='license';$('#application-title').textContent=license?'1·2급 자격증 신청서':'수료증 신청서';$('#application-description').textContent=license?'자격 급수를 선택하고 자격증비 입금일을 입력해 주세요.':'교육을 이수한 수강자가 수료증 발급을 신청하는 화면입니다.';$$('.completion-option').forEach(x=>x.classList.toggle('hidden',license));$$('.license-option').forEach(x=>x.classList.toggle('hidden',!license));$$('[data-apply-mode]').forEach(x=>x.classList.toggle('active',x.dataset.applyMode===mode));const value=license?(type==='level2'?'level2':'level1'):'completion';$(`input[name=requestType][value=${value}]`).checked=true;updatePayment()}
function updatePayment(){const selected=$('input[name=requestType]:checked');const license=selected&&selected.value!=='completion';$('#payment-wrap').classList.toggle('hidden',!license);$('#payment-wrap input').required=license}$$('input[name=requestType]').forEach(x=>x.onchange=updatePayment);$$('[data-apply-mode]').forEach(x=>x.onclick=()=>setApplyMode(x.dataset.applyMode));
$('#application-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const item={id:crypto.randomUUID(),...f,status:'접수',createdAt:new Date().toISOString()};if(db){const {error}=await db.from('certificate_requests').insert({student_name:f.studentName,student_dob:f.birthDate,student_phone:f.phone,student_email:f.email,student_address:f.address,course_name:f.courseName,completion_date:f.completionDate,request_type:f.requestType,instructor_id:f.instructorId,payment_date:f.paymentDate||null});if(error)return msg('application-message','제출하지 못했습니다. '+error.message,true)}else{const a=store.get('applications');a.unshift(item);store.set('applications',a)}msg('application-message','신청이 접수되었습니다. 담당 강사에게 전달됩니다.');e.target.reset();updatePayment();fillInstructors();updateHomeCount()};
const allowedReportExtensions=['pdf','ppt','pptx'];function resetReportFileUI(){const label=$('#report-file-label'),name=$('#report-file-name');label.classList.remove('has-file');name.classList.remove('selected');name.textContent='파일을 선택해 주세요 · PDF, PPT, PPTX · 최대 20MB'}
$('#report-file').onchange=e=>{const file=e.target.files[0];if(!file)return resetReportFileUI();const ext=(file.name.split('.').pop()||'').toLowerCase();if(!allowedReportExtensions.includes(ext)){e.target.value='';resetReportFileUI();return msg('report-message','PDF, PPT, PPTX 파일만 첨부할 수 있습니다.',true)}if(file.size>20*1024*1024){e.target.value='';resetReportFileUI();return msg('report-message','첨부파일은 20MB 이하만 가능합니다.',true)}$('#report-file-label').classList.add('has-file');$('#report-file-name').classList.add('selected');$('#report-file-name').textContent=`선택 완료: ${file.name} (${(file.size/1024/1024).toFixed(1)}MB)`;msg('report-message','교육자료가 첨부되었습니다.')};
$('#report-form').onsubmit=async e=>{e.preventDefault();if(!currentUser)return openLogin();const fd=new FormData(e.target),f=Object.fromEntries(fd),file=fd.get('ppt');if(!file||!file.size)return msg('report-message','PDF 또는 PPT 교육자료를 첨부해 주세요.',true);const ext=(file.name.split('.').pop()||'').toLowerCase();if(!allowedReportExtensions.includes(ext))return msg('report-message','PDF, PPT, PPTX 파일만 첨부할 수 있습니다.',true);let pptPath='';if(file.size>20*1024*1024)return msg('report-message','첨부파일은 20MB 이하만 가능합니다.',true);if(db){pptPath=`${currentUser.id}/${Date.now()}-${file.name}`;const {error}=await db.storage.from('education-ppt').upload(pptPath,file,{contentType:file.type||undefined});if(error)return msg('report-message','교육자료 업로드 실패: '+error.message,true)}const item={id:crypto.randomUUID(),...f,instructorId:currentUser.id,pptName:file.name,pptPath,createdAt:new Date().toISOString()};if(db){const {error}=await db.from('education_reports').insert({instructor_id:currentUser.id,instructor_name:f.instructorName,phone:f.phone,course_name:f.courseName,period_start:f.periodStart,period_end:f.periodEnd,total_hours:f.totalHours,student_count:f.studentCount,ppt_path:pptPath,ppt_filename:file.name});if(error)return msg('report-message','제출 실패: '+error.message,true);fetch('/api/log-report-to-sheet',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${(await db.auth.getSession()).data.session?.access_token}`},body:JSON.stringify(item)}).catch(()=>{})}else{const a=store.get('reports');a.unshift(item);store.set('reports',a)}msg('report-message','교육신고서와 교육자료가 함께 제출되었습니다.');e.target.reset();resetReportFileUI();$('#report-instructor-name').value=currentUser.name||''};
$('#add-instructor').onclick=()=>$('#instructor-dialog').showModal();
$('#instructor-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(db){const session=(await db.auth.getSession()).data.session;const r=await fetch('/api/create-instructor',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session?.access_token}`},body:JSON.stringify(f)});const out=await r.json();if(!r.ok)return msg('instructor-message',out.error||'등록 실패',true)}else{const a=store.get('instructors');a.push({id:crypto.randomUUID(),...f,bank_name:f.bankName,bank_account:f.bankAccount,account_holder:f.accountHolder});store.set('instructors',a)}msg('instructor-message','강사가 등록되었습니다. 로그인 안내 메일이 발송됩니다.');e.target.reset();fillInstructors();setTimeout(()=>{e.target.closest('dialog').close();loadDashboard()},700)};
$$('.tabs button').forEach(b=>b.onclick=()=>{activePanel=b.dataset.panel;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$('.filters').classList.toggle('hidden',activePanel!=='requests');renderTable()});$('#list-search').oninput=renderTable;$('#type-filter').onchange=renderTable;
async function loadDashboard(){if(!currentUser)return;$('#dashboard-title').textContent=currentUser.role==='admin'?'운영자 통합 현황':'강사 업무 현황';$('#dashboard-desc').textContent=currentUser.role==='admin'?'전체 강사와 신청 현황을 총괄합니다.':'내 수강자와 수료·자격증 신청을 확인합니다.';let apps,reports,ins;if(db){let q=db.from('certificate_requests').select('*').order('created_at',{ascending:false});if(currentUser.role==='instructor')q=q.eq('instructor_id',currentUser.id);apps=(await q).data||[];let rq=db.from('education_reports').select('*').order('created_at',{ascending:false});if(currentUser.role==='instructor')rq=rq.eq('instructor_id',currentUser.id);reports=(await rq).data||[];ins=await instructors()}else{apps=store.get('applications');reports=store.get('reports');ins=store.get('instructors');if(currentUser.role==='instructor'){apps=apps.filter(x=>x.instructorId===currentUser.id);reports=reports.filter(x=>x.instructorId===currentUser.id)}}rows={requests:apps,reports,instructors:ins};$('#metric-all').textContent=apps.length;$('#metric-completion').textContent=apps.filter(x=>(x.requestType||x.request_type)==='completion').length;$('#metric-license').textContent=apps.filter(x=>(x.requestType||x.request_type)!=='completion').length;$('#metric-pending').textContent=apps.filter(x=>(x.status||'접수')==='접수').length;renderTable()}
function renderTable(){let data=rows[activePanel]||[],head='';if(activePanel==='requests'){const q=$('#list-search').value.toLowerCase(),t=$('#type-filter').value;data=data.filter(x=>(!t||(x.requestType||x.request_type)===t)&&(`${x.studentName||x.student_name||''} ${x.courseName||x.course_name||''}`).toLowerCase().includes(q));head='<tr><th>신청일</th><th>성명</th><th>구분</th><th>과정</th><th>입금일</th><th>연락처</th><th>상태</th></tr>';data=data.map(x=>`<tr><td>${fmt(x.createdAt||x.created_at)}</td><td><b>${x.studentName||x.student_name}</b></td><td>${typeName(x.requestType||x.request_type)}</td><td>${x.courseName||x.course_name}</td><td>${fmt(x.paymentDate||x.payment_date)}</td><td>${x.phone||x.student_phone||'-'}</td><td><span class="pill pending">${x.status||'접수'}</span></td></tr>`)}else if(activePanel==='reports'){head='<tr><th>신고일</th><th>강사</th><th>과정</th><th>기간</th><th>시간</th><th>인원</th><th>PPT</th></tr>';data=data.map(x=>`<tr><td>${fmt(x.createdAt||x.created_at)}</td><td>${x.instructorName||x.instructor_name}</td><td><b>${x.courseName||x.course_name}</b></td><td>${fmt(x.periodStart||x.period_start)} ~ ${fmt(x.periodEnd||x.period_end)}</td><td>${x.totalHours||x.total_hours}시간</td><td>${x.studentCount||x.student_count}명</td><td>${x.pptName||x.ppt_filename||'-'}</td></tr>`)}else{head='<tr><th>성명</th><th>아이디</th><th>연락처</th><th>은행</th><th>계좌번호</th><th>예금주</th></tr>';data=data.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.email}</td><td>${x.phone||'-'}</td><td>${x.bank_name||x.bankName||'-'}</td><td>${x.bank_account||x.bankAccount||'-'}</td><td>${x.account_holder||x.accountHolder||'-'}</td></tr>`)}$('#table-head').innerHTML=head;$('#table-body').innerHTML=data.join('');$('#empty-state').classList.toggle('hidden',data.length>0)}
function updateHomeCount(){$('#home-count').textContent=store.get('applications').filter(x=>new Date(x.createdAt).toDateString()===new Date().toDateString()).length+'건'}
renderAuth();fillInstructors();updatePayment();updateHomeCount();const initial=location.hash.slice(1);route(['apply','report','dashboard'].includes(initial)?initial:'home');
