const CONFIG=window.APP_CONFIG||{};
const configured=CONFIG.SUPABASE_URL&&!CONFIG.SUPABASE_URL.includes('YOUR-')&&CONFIG.SUPABASE_ANON_KEY&&!CONFIG.SUPABASE_ANON_KEY.includes('YOUR-');
const db=configured&&window.supabase?window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY):null;
const seedInstructors=[];
const store={get(k,f=[]){try{return JSON.parse(localStorage.getItem('baeumon_'+k))||f}catch{return f}},set(k,v){localStorage.setItem('baeumon_'+k,JSON.stringify(v))}};
if(!store.get('instructors').length)store.set('instructors',seedInstructors);
let currentUser=db?store.get('session',null):null,activePanel='requests',rows=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function setupPasswordToggles(){$$('input[type="password"]').forEach(input=>{const wrap=document.createElement('span');wrap.className='password-field';input.parentNode.insertBefore(wrap,input);wrap.appendChild(input);const button=document.createElement('button');button.type='button';button.className='password-toggle';button.textContent='👁';button.setAttribute('aria-label','비밀번호 보기');button.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'🙈':'👁';button.setAttribute('aria-label',show?'비밀번호 숨기기':'비밀번호 보기')};wrap.appendChild(button)})}
const typeName=t=>({completion:'수료증',level1:'1급 자격증',level2:'2급 자격증'}[t]||t);
const fmt=d=>d?new Date(d).toLocaleDateString('ko-KR'):'-';
function route(name){if((name==='report'||name==='dashboard')&&!currentUser){name='instructor-login'}$$('.page').forEach(x=>x.classList.toggle('active',x.id===name));$$('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===name));scrollTo({top:0});if(name==='dashboard')loadDashboard();location.hash=name}
$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route,b.dataset.type));
function renderAuth(){const logged=!!currentUser;$$('.auth-only').forEach(x=>x.classList.toggle('hidden',!logged));$$('.admin-only').forEach(x=>x.classList.toggle('hidden',currentUser?.role!=='admin'));$$('.login-choice').forEach(x=>x.classList.toggle('hidden',logged));$('#logout').classList.toggle('hidden',!logged);$('#user-badge').textContent=logged?`${currentUser.name||'사용자'} · ${currentUser.role==='admin'?'운영자':'강사'}`:'';if(logged)$('#report-instructor-name').value=currentUser.name||''}
$('#quick-report').onclick=()=>currentUser?route('report'):route('instructor-login');$$('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function openLogin(){route('instructor-login')}
$('#logout').onclick=async()=>{if(db)await db.auth.signOut();currentUser=null;store.set('session',null);renderAuth();route('home')};
async function handleLogin(form,expectedRole,messageId){const f=Object.fromEntries(new FormData(form));if(!db)return msg(messageId,'안전한 로그인을 사용하려면 Supabase 운영 환경 연결이 필요합니다.',true);const {data,error}=await db.auth.signInWithPassword({email:f.email,password:f.password});if(error)return msg(messageId,'아이디 또는 비밀번호를 확인해 주세요.',true);const {data:user}=await db.from('profiles').select('*').eq('id',data.user.id).single();if(!user)return msg(messageId,'등록된 계정 정보를 찾을 수 없습니다.',true);if(user.role!==expectedRole){await db.auth.signOut();return msg(messageId,expectedRole==='admin'?'운영자 계정이 아닙니다.':'강사 계정이 아닙니다.',true)}currentUser=user;store.set('session',currentUser);renderAuth();route('dashboard')}
$('#operator-login-form').onsubmit=async e=>{e.preventDefault();await handleLogin(e.target,'admin','operator-login-message')};
$('#instructor-login-form').onsubmit=async e=>{e.preventDefault();await handleLogin(e.target,'instructor','instructor-login-message')};
$$('[data-auth-view]').forEach(b=>b.onclick=()=>{const page=b.closest('.login-page');page.querySelectorAll('.account-switch button').forEach(x=>x.classList.toggle('active',x===b));page.querySelectorAll('.auth-form').forEach(x=>x.classList.toggle('hidden',x.id!==b.dataset.authView))});
function validSignup(f,messageId){if(f.password.length<8){msg(messageId,'비밀번호는 8자 이상 입력해 주세요.',true);return false}if(f.password!==f.passwordConfirm){msg(messageId,'비밀번호 확인이 일치하지 않습니다.',true);return false}return true}
$('#instructor-signup-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(!validSignup(f,'instructor-signup-message'))return;if(!db)return msg('instructor-signup-message','강사 가입은 Supabase 운영 환경 연결 후 사용할 수 있습니다.',true);const {error}=await db.auth.signUp({email:f.email,password:f.password,options:{data:{name:f.name,phone:f.phone,bank_name:f.bankName,bank_account:f.bankAccount,account_holder:f.accountHolder}}});if(error)return msg('instructor-signup-message',error.message,true);msg('instructor-signup-message','가입이 완료되었습니다. 입력한 아이디와 비밀번호로 로그인해 주세요.');e.target.reset()};
$('#operator-signup-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(!validSignup(f,'operator-signup-message'))return;if(!db)return msg('operator-signup-message','운영자 가입은 Supabase 운영 환경 연결 후 사용할 수 있습니다.',true);const {error}=await db.auth.signUp({email:f.email,password:f.password,options:{data:{name:f.name}}});if(error)return msg('operator-signup-message',error.message,true);msg('operator-signup-message','운영자 가입이 완료되었습니다. 바로 로그인해 주세요.');e.target.reset()};
$$('.forgot-password').forEach(b=>b.onclick=async()=>{const form=b.closest('form'),email=form.elements.email.value,id=b.dataset.loginRole==='admin'?'operator-login-message':'instructor-login-message';if(!email)return msg(id,'먼저 아이디(이메일)를 입력해 주세요.',true);if(!db)return msg(id,'비밀번호 찾기는 Supabase 운영 환경 연결 후 사용할 수 있습니다.',true);const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});msg(id,error?error.message:'비밀번호 재설정 메일을 보냈습니다.',!!error)});
function msg(id,text,error=false){const el=$('#'+id);el.textContent=text;el.style.color=error?'#b54332':'#256c54'}
async function instructors(){if(db){const {data}=await db.from('instructor_directory').select('*').order('name');return data||[]}return store.get('instructors',seedInstructors)}
async function fillInstructors(){const list=await instructors(),options='<option value="">강사를 선택해 주세요</option>'+list.map(i=>`<option value="${i.id}">${i.name}</option>`).join('');$('#application-instructor').innerHTML=options;$('#license-instructor').innerHTML=options;$('#license-instructor').onchange=()=>{const i=list.find(x=>x.id===$('#license-instructor').value);$('#license-bank-guide').textContent=i?.bank_name?`자격증비 입금 계좌: ${i.bank_name} ${i.bank_account} (${i.account_holder})`:''}}
async function submitApplication(form,messageId){const f=Object.fromEntries(new FormData(form)),item={id:crypto.randomUUID(),...f,status:'접수',emailStatus:f.requestType==='completion'?'발송대기':'해당없음',createdAt:new Date().toISOString()};if(db){const {error}=await db.from('certificate_requests').insert({student_name:f.studentName,student_dob:f.birthDate,student_phone:f.phone,student_email:f.email,student_address:f.address||null,course_name:f.courseName,completion_date:f.completionDate,request_type:f.requestType,instructor_id:f.instructorId,payment_date:f.paymentDate||null});if(error)return msg(messageId,'제출하지 못했습니다. '+error.message,true);const token=(await db.auth.getSession()).data.session?.access_token;if(token)fetch('/api/log-application-to-sheet',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify(item)}).catch(()=>{})}else{const a=store.get('applications');a.unshift(item);store.set('applications',a)}msg(messageId,f.requestType==='completion'?'수료증 신청이 접수되었습니다. 발급 후 입력한 이메일로 전송됩니다.':'자격증 신청이 접수되었습니다. 담당 강사가 입금일을 확인합니다.');form.reset();fillInstructors();updateHomeCount()}
$('#application-form').onsubmit=async e=>{e.preventDefault();await submitApplication(e.target,'application-message')};
$('#license-form').onsubmit=async e=>{e.preventDefault();await submitApplication(e.target,'license-message')};
const allowedReportExtensions=['pdf','ppt','pptx'];function resetReportFileUI(){const label=$('#report-file-label'),name=$('#report-file-name');label.classList.remove('has-file');name.classList.remove('selected');name.textContent='파일을 선택해 주세요 · PDF, PPT, PPTX · 최대 20MB'}
function attachmentDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('baeumon-files',1);req.onupgradeneeded=()=>req.result.createObjectStore('reports');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveDemoFile(id,file){const d=await attachmentDB();return new Promise((resolve,reject)=>{const tx=d.transaction('reports','readwrite');tx.objectStore('reports').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function openReportFile(id,path){if(db&&path){const {data,error}=await db.storage.from('education-ppt').createSignedUrl(path,120);if(error)return alert('교육자료를 열지 못했습니다: '+error.message);return window.open(data.signedUrl,'_blank')}const d=await attachmentDB(),file=await new Promise((resolve,reject)=>{const req=d.transaction('reports').objectStore('reports').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});if(!file)return alert('이 브라우저에 저장된 첨부파일이 없습니다. 실제 운영에서는 Supabase 저장소 연결이 필요합니다.');window.open(URL.createObjectURL(file),'_blank')}
$('#report-file').onchange=e=>{const file=e.target.files[0];if(!file)return resetReportFileUI();const ext=(file.name.split('.').pop()||'').toLowerCase();if(!allowedReportExtensions.includes(ext)){e.target.value='';resetReportFileUI();return msg('report-message','PDF, PPT, PPTX 파일만 첨부할 수 있습니다.',true)}if(file.size>20*1024*1024){e.target.value='';resetReportFileUI();return msg('report-message','첨부파일은 20MB 이하만 가능합니다.',true)}$('#report-file-label').classList.add('has-file');$('#report-file-name').classList.add('selected');$('#report-file-name').textContent=`선택 완료: ${file.name} (${(file.size/1024/1024).toFixed(1)}MB)`;msg('report-message','교육자료가 첨부되었습니다.')};
$('#report-form').onsubmit=async e=>{e.preventDefault();if(!currentUser)return openLogin();const fd=new FormData(e.target),f=Object.fromEntries(fd),file=fd.get('ppt');if(!file||!file.size)return msg('report-message','PDF 또는 PPT 교육자료를 첨부해 주세요.',true);const ext=(file.name.split('.').pop()||'').toLowerCase();if(!allowedReportExtensions.includes(ext))return msg('report-message','PDF, PPT, PPTX 파일만 첨부할 수 있습니다.',true);let pptPath='';if(file.size>20*1024*1024)return msg('report-message','첨부파일은 20MB 이하만 가능합니다.',true);const item={id:crypto.randomUUID(),...f,instructorId:currentUser.id,pptName:file.name,pptPath,createdAt:new Date().toISOString()};if(db){pptPath=`${currentUser.id}/${Date.now()}-${file.name}`;item.pptPath=pptPath;const {error}=await db.storage.from('education-ppt').upload(pptPath,file,{contentType:file.type||undefined});if(error)return msg('report-message','교육자료 업로드 실패: '+error.message,true);const {error:insertError}=await db.from('education_reports').insert({id:item.id,instructor_id:currentUser.id,instructor_name:f.instructorName,phone:f.phone,course_name:f.courseName,period_start:f.periodStart,period_end:f.periodEnd,total_hours:f.totalHours,student_count:f.studentCount,ppt_path:pptPath,ppt_filename:file.name});if(insertError)return msg('report-message','제출 실패: '+insertError.message,true);fetch('/api/log-report-to-sheet',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${(await db.auth.getSession()).data.session?.access_token}`},body:JSON.stringify(item)}).catch(()=>{})}else{await saveDemoFile(item.id,file);const a=store.get('reports');a.unshift(item);store.set('reports',a)}msg('report-message','교육신고서와 교육자료가 함께 제출되었습니다. 업무 현황에서 파일을 열 수 있습니다.');e.target.reset();resetReportFileUI();$('#report-instructor-name').value=currentUser.name||''};
$('#add-instructor').onclick=()=>$('#instructor-dialog').showModal();
$('#instructor-form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(!db)return msg('instructor-message','강사 계정 등록은 Supabase 운영 환경 연결 후 사용할 수 있습니다.',true);const session=(await db.auth.getSession()).data.session;const r=await fetch('/api/create-instructor',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session?.access_token}`},body:JSON.stringify(f)});const out=await r.json();if(!r.ok)return msg('instructor-message',out.error||'등록 실패',true);msg('instructor-message','강사 계정이 등록되었습니다. 아이디와 임시 비밀번호를 강사에게 안전하게 전달해 주세요.');e.target.reset();fillInstructors();setTimeout(()=>{e.target.closest('dialog').close();loadDashboard()},700)};
$$('.tabs button').forEach(b=>b.onclick=()=>{activePanel=b.dataset.panel;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$('.filters').classList.toggle('hidden',activePanel!=='requests');renderTable()});$('#list-search').oninput=renderTable;$('#type-filter').onchange=renderTable;
async function loadDashboard(){if(!currentUser)return;$('#dashboard-title').textContent=currentUser.role==='admin'?'운영자 통합 현황':'강사 업무 현황';$('#dashboard-desc').textContent=currentUser.role==='admin'?'강사 이름으로 수강생과 신청 내역을 검색하고 인쇄할 수 있습니다.':'내 수강자의 수료증·자격증 신청과 교육자료를 확인합니다.';let apps,reports,ins=await instructors();if(db){let q=db.from('certificate_requests').select('*').order('created_at',{ascending:false});if(currentUser.role==='instructor')q=q.eq('instructor_id',currentUser.id);apps=(await q).data||[];let rq=db.from('education_reports').select('*').order('created_at',{ascending:false});if(currentUser.role==='instructor')rq=rq.eq('instructor_id',currentUser.id);reports=(await rq).data||[]}else{apps=store.get('applications');reports=store.get('reports');if(currentUser.role==='instructor'){apps=apps.filter(x=>x.instructorId===currentUser.id);reports=reports.filter(x=>x.instructorId===currentUser.id)}}const names=Object.fromEntries(ins.map(i=>[i.id,i.name]));apps=apps.map(x=>({...x,_instructorName:names[x.instructorId||x.instructor_id]||'-'}));reports=reports.map(x=>({...x,_instructorName:x.instructorName||x.instructor_name||names[x.instructorId||x.instructor_id]||'-'}));rows={requests:apps,reports,instructors:ins};$('#metric-all').textContent=apps.length;$('#metric-completion').textContent=apps.filter(x=>(x.requestType||x.request_type)==='completion').length;$('#metric-license').textContent=apps.filter(x=>(x.requestType||x.request_type)!=='completion').length;$('#metric-pending').textContent=apps.filter(x=>(x.status||'접수')==='접수').length;renderTable()}
function renderTable(){let data=rows[activePanel]||[],head='';if(activePanel==='requests'){const q=$('#list-search').value.toLowerCase(),t=$('#type-filter').value;data=data.filter(x=>(!t||(x.requestType||x.request_type)===t)&&(`${x.studentName||x.student_name||''} ${x._instructorName||''} ${x.courseName||x.course_name||''}`).toLowerCase().includes(q));head='<tr><th>신청일</th><th>수강생</th><th>담당 강사</th><th>구분</th><th>과정</th><th>이메일</th><th>입금일</th><th>상태</th></tr>';data=data.map(x=>`<tr><td>${fmt(x.createdAt||x.created_at)}</td><td><b>${x.studentName||x.student_name}</b></td><td>${x._instructorName}</td><td>${typeName(x.requestType||x.request_type)}</td><td>${x.courseName||x.course_name}</td><td>${x.email||x.student_email||'-'}</td><td>${fmt(x.paymentDate||x.payment_date)}</td><td><span class="pill pending">${x.status||'접수'}</span></td></tr>`)}else if(activePanel==='reports'){head='<tr><th>신고일</th><th>강사</th><th>과정</th><th>기간</th><th>시간</th><th>인원</th><th>교육자료</th></tr>';data=data.map(x=>{const file=x.pptName||x.ppt_filename;return `<tr><td>${fmt(x.createdAt||x.created_at)}</td><td>${x._instructorName}</td><td><b>${x.courseName||x.course_name}</b></td><td>${fmt(x.periodStart||x.period_start)} ~ ${fmt(x.periodEnd||x.period_end)}</td><td>${x.totalHours||x.total_hours}시간</td><td>${x.studentCount||x.student_count}명</td><td>${file?`<button class="file-link" data-report-file="${x.id}" data-path="${x.pptPath||x.ppt_path||''}">${file} 열기</button>`:'-'}</td></tr>`})}else{head='<tr><th>성명</th><th>로그인 아이디</th><th>연락처</th><th>은행</th><th>계좌번호</th><th>예금주</th><th>계정 관리</th></tr>';data=data.map(x=>`<tr><td><b>${x.name}</b></td><td>${x.email}</td><td>${x.phone||'-'}</td><td>${x.bank_name||x.bankName||'-'}</td><td>${x.bank_account||x.bankAccount||'-'}</td><td>${x.account_holder||x.accountHolder||'-'}</td><td><button class="reset-password" data-reset-id="${x.id}">임시 비밀번호 재설정</button></td></tr>`)}$('#table-head').innerHTML=head;$('#table-body').innerHTML=data.join('');$('#empty-state').classList.toggle('hidden',data.length>0);$$('[data-report-file]').forEach(b=>b.onclick=()=>openReportFile(b.dataset.reportFile,b.dataset.path));$$('[data-reset-id]').forEach(b=>b.onclick=()=>resetInstructorPassword(b.dataset.resetId))}
async function resetInstructorPassword(instructorId){if(!db)return alert('비밀번호 재설정은 Supabase 운영 환경 연결 후 사용할 수 있습니다.');const newPassword=prompt('강사에게 전달할 새 임시 비밀번호를 입력하세요. (8자 이상)');if(newPassword===null)return;if(newPassword.length<8)return alert('임시 비밀번호는 8자 이상이어야 합니다.');const session=(await db.auth.getSession()).data.session,r=await fetch('/api/reset-instructor-password',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session?.access_token}`},body:JSON.stringify({instructorId,newPassword})}),out=await r.json();if(!r.ok)return alert(out.error||'재설정하지 못했습니다.');alert('임시 비밀번호가 재설정되었습니다. 강사에게 안전하게 전달해 주세요.')}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
$('#export-csv').onclick=()=>{const apps=rows.requests||[],header=['신청일','수강생','담당강사','구분','과정','이메일','연락처','입금일','상태'],lines=[header,...apps.map(x=>[fmt(x.createdAt||x.created_at),x.studentName||x.student_name,x._instructorName,typeName(x.requestType||x.request_type),x.courseName||x.course_name,x.email||x.student_email,x.phone||x.student_phone,fmt(x.paymentDate||x.payment_date),x.status||'접수'])].map(r=>r.map(csvCell).join(','));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`신청자목록-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
$('#print-list').onclick=()=>window.print();
function updateHomeCount(){$('#home-count').textContent=store.get('applications').filter(x=>new Date(x.createdAt).toDateString()===new Date().toDateString()).length+'건'}
setupPasswordToggles();renderAuth();fillInstructors();updateHomeCount();const initial=location.hash.slice(1);route(['apply','license','operator-login','instructor-login','report','dashboard'].includes(initial)?initial:'home');
